<a href="https://colab.research.google.com/github/the-star-boy/Local-repo/blob/main/KNN_Imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [3]:
df=pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [4]:
df.head(2)

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1

In [5]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [7]:
x_train.head(2)

     Age  Pclass     Fare
30  40.0       1  27.7208
10   4.0       3  16.7000

In [37]:
knn= KNNImputer(n_neighbors=2,weights='distance')
#
x_train_trf=knn.fit_transform(x_train)
x_test_trf=knn.transform(x_test)

In [38]:
pd.DataFrame(x_train_trf,columns=x_train.columns)

           Age  Pclass      Fare
0    40.000000     1.0   27.7208
1     4.000000     3.0   16.7000
2    47.000000     3.0    9.0000
3     9.000000     3.0   31.3875
4    20.000000     3.0    9.8458
..         ...     ...       ...
707  30.000000     3.0    8.6625
708  30.631313     3.0    8.7125
709  71.000000     1.0   49.5042
710  28.000000     1.0  221.7792
711  49.795455     1.0   25.9250

[712 rows x 3 columns]

In [39]:
lr=LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred=lr.predict(x_test_trf)
accuracy_score(y_test,y_pred)

0.7094972067039106